/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uniandes.dpoo.galeria.interfaz;

import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

import uniandes.dpoo.galeria.modelo.usuario.Comprador;

/**
 *
 * @author user
 */
public class CompradorPanel extends JPanel {

    /**
     * Creates new form InterfazComprador
     */
	private Comprador comprador;
	private ActionListener principal;
	
    public CompradorPanel(ActionListener principal) {
    	this.principal = principal;
        initComponents();
    }
    
    public Comprador getComprador() {
    	return this.comprador;
    }
    
    public void setComprador(Comprador comprador) {
    	this.comprador = comprador;
    	refrescar();
    }
    
    private void refrescar() {
    	this.removeAll();
    	this.initComponents();
    	this.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    
    private void initComponents() {

    	panelGeneral = new javax.swing.JPanel();
    	panelPerfil = new javax.swing.JPanel();
        perfilLabel = new javax.swing.JLabel();
        iconoPerfilPanel = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        galeriaLabel = new javax.swing.JLabel();
        ofertaPiezasPanel = new javax.swing.JPanel();
        piezasCompradorPanel = new javax.swing.JPanel();
        listaPiezasLabel = new javax.swing.JLabel();
        listaLabel = new javax.swing.JLabel();
        scrollPane1Piezas = new javax.swing.JScrollPane();
        listaPiezasComprador = new javax.swing.JList<>();
        panelBotones = new javax.swing.JPanel();
        comprar = new javax.swing.JButton();
        limiteComprasBoton = new javax.swing.JButton();
        botonOfertarSubasta = new javax.swing.JButton();
        consultarPiezaBoton = new javax.swing.JButton();
        comprarBoton = new javax.swing.JButton();
        devolucionBoton = new javax.swing.JButton();

        this.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPerfil.setBackground(new java.awt.Color(207, 140, 194));
        panelPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        perfilLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        perfilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfilLabel.setText("PERFIL");
        perfilLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        iconoPerfilPanel.setBackground(new java.awt.Color(21, 95, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(iconoPerfilPanel);
        iconoPerfilPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        nombreLabel.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);  
        String nom = "";
        if (this.comprador != null) {
        	nom = comprador.getNombre();
        } 
        nombreLabel.setText(nom);
        

        usuarioLabel.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        usuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        String user = "";
        if (this.comprador != null) {
        	user = comprador.getNombreUsuario();
        }
        usuarioLabel.setText(user);

        saldoLabel.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        saldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int saldo = 0;
        if (this.comprador != null) {
        	saldo = comprador.getSaldo();
        }
        saldoLabel.setText(String.valueOf(saldo));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconoPerfilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(perfilLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioLabel)
                            .addComponent(nombreLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(saldoLabel)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perfilLabel)
                .addGap(38, 38, 38)
                .addComponent(iconoPerfilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(nombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoLabel)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        panelGeneral.add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, 200, 500));

        galeriaLabel.setBackground(new java.awt.Color(255, 255, 255));
        galeriaLabel.setFont(new java.awt.Font("Arial", 1, 56)); // NOI18N
        galeriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        galeriaLabel.setText("Galería Da Vinci");
        galeriaLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelGeneral.add(galeriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 840, 110));

        

       
        //javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    
        JPanel catalogo = new PanelImagenTexto();
        ofertaPiezasPanel = catalogo;
        
        ofertaPiezasPanel.setBackground(new java.awt.Color(137, 164, 185));
        panelGeneral.add(ofertaPiezasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 850, 410));

        piezasCompradorPanel.setBackground(new java.awt.Color(207, 140, 194));
        piezasCompradorPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listaPiezasLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        listaPiezasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaPiezasLabel.setText("LISTA");
        listaPiezasLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listaLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        listaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaLabel.setText("PIEZAS");
        listaLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        
        limiteComprasBoton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        limiteComprasBoton.setText("Aumentar limite de Compras");
        limiteComprasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        
        botonOfertarSubasta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        botonOfertarSubasta.setText("Ofertar en subasta");
        botonOfertarSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	comprador.solicitarAumentoLimite();
            }
        });

        consultarPiezaBoton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        consultarPiezaBoton.setText("Consultar Pieza");
        consultarPiezaBoton.setActionCommand("Consultar Pieza");
        consultarPiezaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });

        comprarBoton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        comprarBoton.setText("Comprar");
        comprarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });

        devolucionBoton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        devolucionBoton.setText("Devolución");
        devolucionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });

        listaPiezasComprador.setBackground(new java.awt.Color(207, 140, 194));
        listaPiezasComprador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaPiezasComprador.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- Pieza 1", "- Pieza 2", "- Pieza 3", "- Pieza 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPane1Piezas.setViewportView(listaPiezasComprador);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(piezasCompradorPanel);
        piezasCompradorPanel.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaLabel)
                    .addComponent(listaPiezasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(scrollPane1Piezas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaPiezasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaLabel)
                .addGap(35, 35, 35)
                .addComponent(scrollPane1Piezas, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        panelGeneral.add(piezasCompradorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 140, -1, -1));

        panelBotones.setBackground(new java.awt.Color(159, 212, 252));

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
        		jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(limiteComprasBoton)
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        				.addComponent(consultarPiezaBoton)
        				.addGap(18, 18, 18)
        				.addComponent(devolucionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
        				.addGap(18, 18, 18)
        				.addComponent(comprarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
        				.addGap(26, 26, 26)
        				.addComponent(botonOfertarSubasta)
        				.addGap(541, 541, 541))
        		);
        jPanel6Layout.setVerticalGroup(
        		jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(limiteComprasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonOfertarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(devolucionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comprarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(consultarPiezaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(22, Short.MAX_VALUE))
        );

        panelGeneral.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 850, -1));

        this.add(panelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1391, 698));
        

        //Agregar piezas al catalogo
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton comprar;
    private javax.swing.JLabel perfilLabel;
    private javax.swing.JLabel listaLabel;
    private javax.swing.JLabel galeriaLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JLabel listaPiezasLabel;
    private javax.swing.JList<String> listaPiezasComprador;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JPanel iconoPerfilPanel;
    private javax.swing.JPanel ofertaPiezasPanel;
    private javax.swing.JPanel piezasCompradorPanel;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JScrollPane scrollPane1Piezas;
    private javax.swing.JButton limiteComprasBoton;
    private javax.swing.JButton botonOfertarSubasta;
    private javax.swing.JButton consultarPiezaBoton;
    private javax.swing.JButton comprarBoton;
    private javax.swing.JButton devolucionBoton;
    // End of variables declaration           
    
    

}

