/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package uniandes.dpoo.galeria.interfaz;

import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import uniandes.dpoo.galeria.modelo.usuario.Comprador;
import uniandes.dpoo.galeria.persistencia.PersistenciaComprador;

/**
 *
 * @author user
 */
@SuppressWarnings("serial")
public class RegisterPanel extends JPanel {

    /** Creates new form Register */
    public RegisterPanel(ActionListener listener) {
    	this.listener = listener;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	registerPanel = new javax.swing.JPanel();
    	registerLabel = new javax.swing.JLabel();
        datosPanel = new javax.swing.JPanel();
        confirmPass = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        identificacion = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        termsConds = new javax.swing.JCheckBox();
        signUp = new javax.swing.JButton();

        this.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel.setBackground(new java.awt.Color(0, 153, 204));
        registerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register");
        registerPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 210, 50));

        this.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 80));

        datosPanel.setBackground(new java.awt.Color(0, 51, 102));
        datosPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        datosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmPass.setText("Confirm Password");
        confirmPass.setToolTipText("");
        confirmPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });
        datosPanel.add(confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 272, 33));

        name.setText("Enter Full Name");
        name.setToolTipText("");
        name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });
        datosPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 272, 33));

        identificacion.setText("Enter Number ID");
        identificacion.setToolTipText("");
        identificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });
        datosPanel.add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 272, 33));

        edad.setText("Enter Age");
        edad.setToolTipText("");
        edad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        datosPanel.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 272, 33));

        usuario.setText("Enter UserName");
        usuario.setToolTipText("");
        usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        datosPanel.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 272, 33));

        phone.setText("Enter Number Phone");
        phone.setToolTipText("");
        phone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        datosPanel.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 272, 33));

        email.setText("Enter Email");
        email.setToolTipText("");
        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        datosPanel.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 272, 33));

        pass.setText("Enter Password");
        pass.setToolTipText("");
        pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        datosPanel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 272, 33));

        termsConds.setForeground(new java.awt.Color(255, 255, 255));
        termsConds.setText("I agree with terms and conditions");
        termsConds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        datosPanel.add(termsConds, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        signUp.setBackground(new java.awt.Color(0, 153, 204));
        signUp.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Sign Up");
        signUp.setActionCommand("COMPRADOR");
        signUp.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
                String nombre = name.getText();
                
                String id = identificacion.getText();
                long identificacion = Long.parseLong(id);
                
                String age = edad.getText();
                int edad = Integer.parseInt(age);
                
                String user = usuario.getText();
                
                String contraseña = pass.getText();
                
                String numeroTelefono = phone.getText();
                
                String correo = email.getText();
                int saldo = 0;
                
                String conpass = confirmPass.getText();
                
                if (conpass.equals(contraseña) && termsConds.isSelected()) {
                	Comprador nuevoComprador = new Comprador(nombre, identificacion, edad, user, contraseña, numeroTelefono,correo,saldo);
                	PersistenciaComprador.guardarComprador(nuevoComprador);
                	signUp.addActionListener(listener);
        			
                }
                else if (termsConds.isSelected() == false){
                	JOptionPane.showMessageDialog(null, "Debes aceptar los términos y condiciones.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else {
                	JOptionPane.showMessageDialog(null, "Contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
                }
        	}
          
        });
        datosPanel.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 120, 50));

        this.add(datosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 560));

        
    }                                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton signUp;
    private javax.swing.JCheckBox termsConds;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel datosPanel;
    private javax.swing.JTextField confirmPass;
    private javax.swing.JTextField name;
    private javax.swing.JTextField identificacion;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField email;
    private javax.swing.JTextField pass;
    private ActionListener listener;
    // End of variables declaration                   

}
